# Generated by Django 2.2 on 2019-06-01 16:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('partidos_jugados', models.PositiveIntegerField(default=0)),
                ('partidos_ganados', models.PositiveIntegerField(default=0)),
                ('partidos_perdidos', models.PositiveIntegerField(default=0)),
                ('partidos_empatados', models.PositiveIntegerField(default=0)),
                ('a_favor', models.PositiveIntegerField(default=0)),
                ('en_contra', models.PositiveIntegerField(default=0)),
                ('diferencia', models.IntegerField(default=0)),
                ('puntos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-puntos', '-diferencia', '-a_favor', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('vuelta', models.CharField(choices=[('N', 'No'), ('S', 'Simetrica'), ('A', 'Asimetrica')], max_length=1)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='torneos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_ronda', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='torneos.Torneo')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcador_local', models.PositiveIntegerField(blank=True, null=True)),
                ('marcador_visitante', models.PositiveIntegerField(blank=True, null=True)),
                ('jugado', models.BooleanField(default=False)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partido_local', to='torneos.Equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partido_visitante', to='torneos.Equipo')),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='torneos.Ronda')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='torneos.Torneo'),
        ),
        migrations.AddConstraint(
            model_name='torneo',
            constraint=models.UniqueConstraint(fields=('nombre', 'usuario'), name='unique_nombre_torneo'),
        ),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.UniqueConstraint(fields=('nombre', 'torneo'), name='unique_nombre_equipo'),
        ),
    ]
